[project]
name = "badpdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pikepdf>=9.5.1",
    "pillow>=11.1.0",
    "pyvlq>=0.1.1",
]
