export class App extends PDFObject {
    static _getPlatform(platform: any): "WIN" | "MAC" | "UNIX";
    static _getLanguage(language: any): "CHS" | "CHT" | "DAN" | "DEU" | "ESP" | "FRA" | "ITA" | "KOR" | "JPN" | "NLD" | "NOR" | "PTB" | "ENU" | "SUO" | "SVE";
    constructor(data: any);
    _constants: Readonly<{
        align: Readonly<{
            left: 0;
            center: 1;
            right: 2;
            top: 3;
            bottom: 4;
        }>;
    }>;
    _focusRect: boolean;
    _fs: FullScreen;
    _language: string;
    _openInPlace: boolean;
    _platform: string;
    _runtimeHighlight: boolean;
    _runtimeHighlightColor: string[];
    _thermometer: Thermometer;
    _toolbar: boolean;
    _document: any;
    _proxyHandler: any;
    _objects: any;
    _eventDispatcher: EventDispatcher;
    _timeoutIds: WeakMap<object, any>;
    _timeoutIdsRegistry: FinalizationRegistry<any>;
    _timeoutCallbackIds: Map<any, any>;
    _timeoutCallbackId: number;
    _globalEval: any;
    _externalCall: any;
    _dispatchEvent(pdfEvent: any): void;
    _registerTimeoutCallback(cExpr: any): number;
    _unregisterTimeoutCallback(id: any): void;
    _evalCallback({ callbackId, interval }: {
        callbackId: any;
        interval: any;
    }): void;
    _registerTimeout(callbackId: any, interval: any): any;
    _unregisterTimeout(timeout: any): void;
    _cleanTimeout({ callbackId, interval }: {
        callbackId: any;
        interval: any;
    }): void;
    set activeDocs(_: any[]);
    get activeDocs(): any[];
    set calculate(calculate: any);
    get calculate(): any;
    set constants(_: Readonly<{
        align: Readonly<{
            left: 0;
            center: 1;
            right: 2;
            top: 3;
            bottom: 4;
        }>;
    }>);
    get constants(): Readonly<{
        align: Readonly<{
            left: 0;
            center: 1;
            right: 2;
            top: 3;
            bottom: 4;
        }>;
    }>;
    set focusRect(val: boolean);
    get focusRect(): boolean;
    set formsVersion(_: 21.00720099);
    get formsVersion(): 21.00720099;
    set fromPDFConverters(_: any[]);
    get fromPDFConverters(): any[];
    set fs(_: FullScreen);
    get fs(): FullScreen;
    set language(_: string);
    get language(): string;
    set media(_: any);
    get media(): any;
    set monitors(_: any[]);
    get monitors(): any[];
    set numPlugins(_: number);
    get numPlugins(): number;
    set openInPlace(val: boolean);
    get openInPlace(): boolean;
    set platform(_: string);
    get platform(): string;
    set plugins(_: any[]);
    get plugins(): any[];
    set printColorProfiles(_: any[]);
    get printColorProfiles(): any[];
    set printerNames(_: any[]);
    get printerNames(): any[];
    set runtimeHighlight(val: boolean);
    get runtimeHighlight(): boolean;
    set runtimeHighlightColor(val: string[]);
    get runtimeHighlightColor(): string[];
    set thermometer(_: Thermometer);
    get thermometer(): Thermometer;
    set toolbar(val: boolean);
    get toolbar(): boolean;
    set toolbarHorizontal(value: boolean);
    get toolbarHorizontal(): boolean;
    set toolbarVertical(value: boolean);
    get toolbarVertical(): boolean;
    set viewerType(_: "PDF.js");
    get viewerType(): "PDF.js";
    set viewerVariation(_: "Full");
    get viewerVariation(): "Full";
    set viewerVersion(_: 21.00720099);
    get viewerVersion(): 21.00720099;
    addMenuItem(): void;
    addSubMenu(): void;
    addToolButton(): void;
    alert(cMsg: any, nIcon?: number, nType?: number, cTitle?: string, oDoc?: any, oCheckbox?: any): 0 | 1 | 3 | 4;
    beep(): void;
    beginPriv(): void;
    browseForDoc(): void;
    clearInterval(oInterval: any): void;
    clearTimeOut(oTime: any): void;
    endPriv(): void;
    execDialog(): void;
    execMenuItem(item: any): void;
    getNthPlugInName(): void;
    getPath(): void;
    goBack(): void;
    goForward(): void;
    hideMenuItem(): void;
    hideToolbarButton(): void;
    launchURL(): void;
    listMenuItems(): void;
    listToolbarButtons(): void;
    loadPolicyFile(): void;
    mailGetAddrs(): void;
    mailMsg(): void;
    newDoc(): void;
    newCollection(): void;
    newFDF(): void;
    openDoc(): void;
    openFDF(): void;
    popUpMenu(): void;
    popUpMenuEx(): void;
    removeToolButton(): void;
    response(cQuestion: any, cTitle?: string, cDefault?: string, bPassword?: string, cLabel?: string): any;
    setInterval(cExpr: any, nMilliseconds?: number): any;
    setTimeOut(cExpr: any, nMilliseconds?: number): any;
    trustedFunction(): void;
    trustPropagatorFunction(): void;
}
import { PDFObject } from "./pdf_object.js";
import { FullScreen } from "./fullscreen.js";
import { Thermometer } from "./thermometer.js";
import { EventDispatcher } from "./event.js";
